using System.Reflection;
using System.Runtime.Serialization;
using Iyu.Data.ValueConverters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Iyu.Data;

/// <summary>
/// Base <see cref="DbContext"/> that all generated consumer DbContexts
/// (e.g. <c>YesungDbContext</c>) derive from. Automatically registers the
/// <see cref="IyuTimestampInterceptor"/> so that every save operation maintains
/// <c>CreatedAt</c>/<c>UpdatedAt</c> invariants.
/// </summary>
/// <remarks>
/// Consumers pass <see cref="DbContextOptions"/> through the standard EF Core
/// DI pipeline. Additional interceptors supplied via <see cref="DbContextOptionsBuilder"/>
/// are preserved — this class only ensures the timestamp interceptor is present.
/// </remarks>
public abstract class IyuDbContext(DbContextOptions options) : DbContext(options)
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        // Idempotent registration — harmless if consumer already added one.
        optionsBuilder.AddInterceptors(new IyuTimestampInterceptor());
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        base.ConfigureConventions(configurationBuilder);
        IyuValueConverters.RegisterAll(configurationBuilder);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        ApplyEnumMemberConverters(modelBuilder);
    }

    /// <summary>
    /// Scans all entity properties for enum types with [EnumMember] attributes
    /// and applies a value converter that stores the EnumMember value (lowercase)
    /// instead of the CLR name (PascalCase). This matches the SQL CHECK constraints
    /// generated by mdd-booster.
    /// </summary>
    private static void ApplyEnumMemberConverters(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entityType.GetProperties())
            {
                var clrType = property.ClrType;
                var underlyingType = Nullable.GetUnderlyingType(clrType) ?? clrType;
                if (!underlyingType.IsEnum) continue;
                if (!HasEnumMemberAttributes(underlyingType)) continue;

                var converterType = typeof(EnumMemberConverter<>).MakeGenericType(underlyingType);
                var converter = (ValueConverter)Activator.CreateInstance(converterType)!;
                property.SetValueConverter(converter);
            }
        }
    }

    private static bool HasEnumMemberAttributes(Type enumType) =>
        enumType.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Any(f => f.GetCustomAttribute<EnumMemberAttribute>() != null);
}

/// <summary>
/// Converts an enum to/from its [EnumMember(Value)] string representation.
/// Falls back to the CLR name if no [EnumMember] attribute is present.
/// </summary>
public class EnumMemberConverter<TEnum> : ValueConverter<TEnum, string>
    where TEnum : struct, Enum
{
    private static readonly Dictionary<TEnum, string> ToDb;
    private static readonly Dictionary<string, TEnum> FromDb;

    static EnumMemberConverter()
    {
        var type = typeof(TEnum);
        var values = Enum.GetValues<TEnum>();
        ToDb = new Dictionary<TEnum, string>(values.Length);
        FromDb = new Dictionary<string, TEnum>(values.Length, StringComparer.OrdinalIgnoreCase);

        foreach (var val in values)
        {
            var name = val.ToString();
            var field = type.GetField(name, BindingFlags.Public | BindingFlags.Static);
            var attr = field?.GetCustomAttribute<EnumMemberAttribute>();
            var dbValue = attr?.Value ?? name;
            ToDb[val] = dbValue;
            FromDb[dbValue] = val;
        }
    }

    public EnumMemberConverter()
        : base(v => ToDb.GetValueOrDefault(v, v.ToString()),
               v => FromDb.GetValueOrDefault(v, default))
    { }
}
