<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Iyu.FileServer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Iyu.Core/Iyu.Core.csproj" />
  </ItemGroup>
</Project>
